project:
  type: website
  output-dir: docs
execute:
  freeze: auto

website:
  title: "BigFish"
  repo-url: https://github.com/fishsizeproject/BigFishGame
  site-url: https://bigfishcardgame.com/
  favicon: /resources/images/BigFish_white.png
  page-navigation: false
  back-to-top-navigation: false
  navbar:
    title: false
    background: primary
    foreground: light
    logo: /resources/images/BigFish_white.png
    pinned: true
    collapse: true
    left:
      - text: "Rules"
        href: pages/rules.qmd
      - text: "Cards"
        menu:
          - text: "Fish cards"
            href: pages/fish-cards.qmd
          - text: "Wildcards"
            href: pages/wildcards.qmd
          - text: "Round-end cards"
            href: pages/round-end-cards.qmd
      - text: "Outreach"
        href: pages/outreach-blog.qmd
      - text: "About Us"
        href: index.qmd#sec-about
      - text: "Get yours"
        href: pages/how-to-buy.qmd
  page-footer:
    left: |
      [![](/resources/icons/envelope-solid-ghost.svg){height="1em"}](mailto:info@fishsizeproject.org) [info@fishsizeproject.org](mailto:info@fishsizeproject.org)<br>
      [![](/resources/icons/github-ghost.svg){height="1em"}](https://github.com/fishsizeproject/) [fishsizeproject](https://github.com/fishsizeproject/)<br><br>
      [Institute of Marine and Antarctic Research](https://www.imas.utas.edu.au/)<br>
      20 Castray Esplanade<br>
      Battery Point TAS 7000<br>
      Australia<br>
    right: |
      <i>We acknowledge the traditional owners of the land on which we live and work.Sovereignty was never ceded </i><img src="/resources/styling/Australian_Aboriginal_Flag.png" class="img-fluid" style="height: 1em;">
      <br><br><br>
      © BigFish Card Game, 2024<br>
      Website created by [Tormey Reimer](https://drtreimer.com)
    center: |
      [<img src="/resources/images/UniTas_IMAS_V_Rev_Col_RGB.png" class="img-fluid" style="width: 20%;">](https://www.imas.utas.edu.au)
      [<img src="/resources/images/fishsize-logo-backed.png" class="img-fluid" style="width: 20%; margin-left: 2.5%;">](https://fishsizeproject.org/)
      [<img src="/resources/images/CMS.png" class="img-fluid" style="width: 27.5%;">](https://marinesocioecology.org)
    border: false
    background: primary
    foreground: light

# Sidebar options:
# id: The identifier for this sidebar.
# title: The sidebar title. Uses the project title if none is specified.
# logo: Path to a logo image that will be displayed in the sidebar.
# search: Include a search control in the sidebar.
# tools: List of sidebar tools (see Sidebar Tools)
# contents: List of navigation items to appear in the sidebar. Can also include section entries which in turn contain sub-lists of navigation items.
# style: The style of sidebar (docked or floating).
# background: The sidebar’s background color (named or hex color).
# foreground: The sidebar’s foreground color (named or hex color).
# border: Whether to show a border on the sidebar (defaults to true for ‘docked’ sidebars)
# alignment: Alignment of the items within the sidebar (left, right, or center)
# collapse-level: The depth at which the sidebar contents should be collapsed by default.
# pinned: When collapsed, pin the collapsed sidebar to the top of the page.
# header: Markdown to place above sidebar content (text or file path)
# footer: Markdown to place below sidebar content (text or file path)

# Different sidebars for different pages
  sidebar:
  - id: "special-sidebar"
    style: "docked"
    border: false
    pinned: false
    contents:
      - section: "Wildcards"
        contents:
        - text: "Blue Groper"
          href: pages/wildcards.qmd#sec-blue-groper
        - text: "Catch or Release"
          href: pages/wildcards.qmd#sec-catch-or-release
        - text: "Citizen science"
          href: pages/wildcards.qmd#sec-citizen-science
        - text: "Centre for Marine Socioecology (CMS)"
          href: pages/wildcards.qmd#sec-cms
        - text: "Delicious bait"
          href: pages/wildcards.qmd#sec-delicious-bait
        - text: "Fishing kayak"
          href: pages/wildcards.qmd#sec-fishing-kayak
        - text: "Fishing rod"
          href: pages/wildcards.qmd#sec-fishing-rod
        - text: "Giant kelp"
          href: pages/wildcards.qmd#sec-giant-kelp
        - text: "Humpback whale"
          href: pages/wildcards.qmd#sec-humpback-whale
        - text: "Illegal fishing"
          href: pages/wildcards.qmd#sec-illegal-fishing
        - text: "Large shark"
          href: pages/wildcards.qmd#sec-large-shark
        - text: "Marine protected area"
          href: pages/wildcards.qmd#sec-marine-protected-area
        - text: "Poor water quality"
          href: pages/wildcards.qmd#sec-poor-water-quality
        - text: "SCUBA equipment"
          href: pages/wildcards.qmd#sec-scuba-equipment
        - text: "Seaweed"
          href: pages/wildcards.qmd#sec-seaweed
        - text: "Severe weather"
          href: pages/wildcards.qmd#sec-severe-weather
        - text: "Shellfish reef"
          href: pages/wildcards.qmd#sec-shellfish-reef
      - text: "-----"
      - section: "Round-End Cards"
        contents:
        - text: "El Niño begins"
          href: pages/round-end-cards.qmd#sec-el-nino-begins
        - text: "Fisheries research occurs"
          href: pages/round-end-cards.qmd#sec-fisheries-research
        - text: "Localised species extinction"
          href: pages/round-end-cards.qmd#sec-localised-species-extinction
        - text: "Ocean acidification"
          href: pages/round-end-cards.qmd#sec-ocean-acidification
        - text: "Plankton swarm occurs"
          href: pages/round-end-cards.qmd#sec-plankton-swarm
        - text: "Seaweed planting occurs"
          href: pages/round-end-cards.qmd#sec-seaweed-planting
        - text: "Fisheries impose upper size limit"
          href: pages/round-end-cards.qmd#sec-upper-size-limit
        - text: "Long spined sea urchins arrive"
          href: pages/round-end-cards.qmd#sec-urchins-arrive
        - text: "END GAME"
          href: pages/round-end-cards.qmd#sec-end-game
      - text: "-----"
      - text: " Game Setup & Rules"
        href: pages/rules.qmd
  - id: "fish-sidebar"
    style: "docked"
    border: false
    pinned: false
    contents:
      - text: "Abalone"
        href: pages/fish-cards.qmd#sec-abalone
      - text: "Australian Red Cod"
        href: pages/fish-cards.qmd#sec-australian-red-cod
      - text: "Banded Morwong"
        href: pages/fish-cards.qmd#sec-banded-morwong
      - text: "Bastard Trumpeter"
        href: pages/fish-cards.qmd#sec-bastard-trumpeter
      - text: "Blue Fin Tuna"
        href: pages/fish-cards.qmd#sec-blue-fin-tuna
      - text: "Blue Mackerel"
        href: pages/fish-cards.qmd#sec-blue-mackerel
      - text: "Bluethroat Wrasse"
        href: pages/fish-cards.qmd#sec-bluethroat-wrasse
      - text: "Brownstriped Leatherjacket"
        href: pages/fish-cards.qmd#sec-brownstriped-leatherjacket
      - text: "Draughtboard Shark"
        href: pages/fish-cards.qmd#sec-draughtboard-shark
      - text: "Flounder"
        href: pages/fish-cards.qmd#sec-flounder
      - text: "Herring Cale"
        href: pages/fish-cards.qmd#sec-herring-cale
      - text: "Longfin Pike"
        href: pages/fish-cards.qmd#sec-longfin-pike
      - text: "Longsnout Boarfish"
        href: pages/fish-cards.qmd#sec-longsnout-boarfish
      - text: "Marblefish"
        href: pages/fish-cards.qmd#sec-marblefish
      - text: "Purple Wrasse"
        href: pages/fish-cards.qmd#sec-purple-wrasse
      - text: "Red Rock Crab"
        href: pages/fish-cards.qmd#sec-red-rock-crab
      - text: "Sand Flathead"
        href: pages/fish-cards.qmd#sec-sand-flathead
      - text: "Senator Wrasse"
        href: pages/fish-cards.qmd#sec-senator-wrasse
      - text: "Shaws Cowfish"
        href: pages/fish-cards.qmd#sec-shaws-cowfish
      - text: "Southern Rock Lobster"
        href: pages/fish-cards.qmd#sec-southern-rock-lobster
      - text: "Toothbrush Leather Jacket"
        href: pages/fish-cards.qmd#sec-toothbrush-leather-jacket
      - text: "Yellowtail Kingfish"
        href: pages/fish-cards.qmd#sec-yellowtail-kingfish
  - id: "placeholder-sidebar"
    style: "docked"
    border: false
    pinned: false
    contents:
      - text: "Main"
        href: pages/new-page-with-sidebar.qmd#sec-main-title
      - text: "Section"
        href: pages/new-page-with-sidebar.qmd#sec-section-title
      - text: "Sub-section 1"
        href: pages/new-page-with-sidebar.qmd#sec-subtitle-1
      - text: "Sub-section 2"
        href: pages/new-page-with-sidebar.qmd#sec-subtitle-2
      - text: "Button"
        href: pages/new-page-with-sidebar.qmd#sec-button

format:
  html:
    logo: /resources/images/fishsize-logo-backed.png
    theme: [lux, resources/styling/theming.scss]
    css: /resources/styling/styles.css
    toc: false
    anchor-sections: false
    link-external-newwindow: true
    page-layout: full
    grid:
      sidebar-width: 400px
      body-width: 1400px
      margin-width: 0px
      gutter-width: 0px

editor: source


