project:
  type: website
  output-dir: docs
execute:
  freeze: auto

website:
  title: "BigFish"
  repo-url: https://github.com/fishsizeproject/BigFishGame
  site-url: https://bigfishcardgame.com/
  favicon: /resources/images/BigFish-notext.jpg
  page-navigation: false
  back-to-top-navigation: true
  navbar:
    logo: /resources/images/BigFish-notext.jpg
    pinned: true
    collapse: false
    left:
      - text: "Rules"
        href: pages/rules.qmd
      - text: "Cards"
        menu:
          - text: "Fish cards"
            href: pages/fish-cards.qmd
          - text: "Wildcards"
            href: pages/special-cards.qmd#sec-wildcards
          - text: "Round-end cards"
            href: pages/special-cards.qmd#sec-round-end-cards
      - text: "Media & Events"
        href: pages/media-events.qmd
      - text: "About Us"
        href: pages/about.qmd
      - text: "How To Buy"
        href: pages/how-to-buy.qmd
  page-footer:
    left: |
      [![](/resources/icons/ic--baseline-mail.svg)](mailto:info@fishsizeproject.org) [info@fishsizeproject.org](mailto:info@fishsizeproject.org)<br>
      [![](/resources/icons/mdi--github.svg)](https://github.com/fishsizeproject/) [fishsizeproject](https://github.com/fishsizeproject/)<br><br>
      [Institute of Marine and Antarctic Research](https://www.imas.utas.edu.au/)<br>
      20 Castray Esplanade<br>
      Battery Point TAS 7000<br>
      Australia<br>
    right: |
      <i>We acknowledge the traditional owners of the land on which we live and work.<br>
      Sovereignty was never ceded </i><img src="/resources/styling/Australian_Aboriginal_Flag.png" class="img-fluid" style="height: 1em;"> <br><br><br>
      © BigFish Card Game, 2024<br>
      Website created by [Tormey Reimer](https://drtreimer.com)
    center: |
      [<img src="/resources/images/BigFish-notext.jpg" class="img-fluid" style="width: 10vw;">](/index.qmd)
    border: false
    background: primary
    foreground: light

# Different sidebars for different pages
  sidebar:
  - id: special-sidebar
    style: "docked"
    type: dark
    border: false
    pinned: true
    contents:
      - section: "Wildcards"
        contents:
        - text: "Blue Groper"
          href: pages/special-cards.qmd#sec-blue-groper
        - text: "Catch or Release"
          href: pages/special-cards.qmd#sec-catch-or-release
        - text: "Citizen science"
          href: pages/special-cards.qmd#sec-citizen-science
        - text: "Centre for Marine Socioecology (CMS)"
          href: pages/special-cards.qmd#sec-cms
        - text: "Delicious bait"
          href: pages/special-cards.qmd#sec-delicious-bait
        - text: "Fishing kayak"
          href: pages/special-cards.qmd#sec-fishing-kayak
        - text: "Fishing rod"
          href: pages/special-cards.qmd#sec-fishing-rod
        - text: "Giant kelp"
          href: pages/special-cards.qmd#sec-giant-kelp
        - text: "Humpback whale"
          href: pages/special-cards.qmd#sec-humpback-whale
        - text: "Illegal fishing"
          href: pages/special-cards.qmd#sec-illegal-fishing
        - text: "Large shark"
          href: pages/special-cards.qmd#sec-large-shark
        - text: "Marine protected area"
          href: pages/special-cards.qmd#sec-marine-protected-area
        - text: "Poor water quality"
          href: pages/special-cards.qmd#sec-poor-water-quality
        - text: "SCUBA equipment"
          href: pages/special-cards.qmd#sec-scuba-equipment
        - text: "Seaweed"
          href: pages/special-cards.qmd#sec-seaweed
        - text: "Severe weather"
          href: pages/special-cards.qmd#sec-severe-weather
        - text: "Shellfish reef"
          href: pages/special-cards.qmd#sec-shellfish-reef
      - text: "-----"
      - section: "Round-End Cards"
        contents:
        - text: "El Niño begins"
          href: pages/special-cards.qmd#sec-el-nino-begins
        - text: "Fisheries research occurs"
          href: pages/special-cards.qmd#sec-fisheries-research
        - text: "Localised species extinction"
          href: pages/special-cards.qmd#sec-localised-species-extinction
        - text: "Ocean acidification"
          href: pages/special-cards.qmd#sec-ocean-acidification
        - text: "Plankton swarm occurs"
          href: pages/special-cards.qmd#sec-plankton-swarm
        - text: "Seaweed planting occurs"
          href: pages/special-cards.qmd#sec-seaweed-planting
        - text: "Fisheries impose upper size limit"
          href: pages/special-cards.qmd#sec-upper-size-limit
        - text: "Long spined sea urchins arrive"
          href: pages/special-cards.qmd#sec-urchins-arrive
        - text: "END GAME"
          href: pages/special-cards.qmd#sec-end-game
      - text: "-----"
      - text: " Game Setup & Rules"
        href: pages/rules.qmd
  - id: fish-sidebar
    style: "docked"
    type: dark
    border: false
    pinned: true
    contents:
      - text: "Abalone"
        href: pages/fish-cards.qmd#sec-abalone
      - text: "Australian Red Cod"
        href: pages/fish-cards.qmd#sec-australian-red-cod
      - text: "Banded Morwong"
        href: pages/fish-cards.qmd#sec-banded-morwong
      - text: "Bastard Trumpeter"
        href: pages/fish-cards.qmd#sec-bastard-trumpeter
      - text: "Blue Fin Tuna"
        href: pages/fish-cards.qmd#sec-blue-fin-tuna
      - text: "Blue Mackerel"
        href: pages/fish-cards.qmd#sec-blue-mackerel
      - text: "Bluethroat Wrasse"
        href: pages/fish-cards.qmd#sec-bluethroat-wrasse
      - text: "Brownstriped Leatherjacket"
        href: pages/fish-cards.qmd#sec-brownstriped-leatherjacket
      - text: "Draughtboard Shark"
        href: pages/fish-cards.qmd#sec-draughtboard-shark
      - text: "Flounder"
        href: pages/fish-cards.qmd#sec-flounder
      - text: "Herring Cale"
        href: pages/fish-cards.qmd#sec-herring-cale
      - text: "Longfin Pike"
        href: pages/fish-cards.qmd#sec-longfin-pike
      - text: "Longsnout Boarfish"
        href: pages/fish-cards.qmd#sec-longsnout-boarfish
      - text: "Marblefish"
        href: pages/fish-cards.qmd#sec-marblefish
      - text: "Purple Wrasse"
        href: pages/fish-cards.qmd#sec-purple-wrasse
      - text: "Red Rock Crab"
        href: pages/fish-cards.qmd#sec-red-rock-crab
      - text: "Sand Flathead"
        href: pages/fish-cards.qmd#sec-sand-flathead
      - text: "Senator Wrasse"
        href: pages/fish-cards.qmd#sec-senator-wrasse
      - text: "Shaws Cowfish"
        href: pages/fish-cards.qmd#sec-shaws-cowfish
      - text: "Southern Rock Lobster"
        href: pages/fish-cards.qmd#sec-southern-rock-lobster
      - text: "Toothbrush Leather Jacket"
        href: pages/fish-cards.qmd#sec-toothbrush-leather-jacket
      - text: "Yellowtail Kingfish"
        href: pages/fish-cards.qmd#sec-yellowtail-kingfish

format:
  html:
    logo: /resources/images/BigFish-notext.jpg
    theme: [lux, resources/styling/theming.scss]
    css: /resources/styling/styles.css
    toc: false
    anchor-sections: false
    link-external-newwindow: true
    page-layout: full
    grid:
      sidebar-width: 350px
      body-width: 1200px
      margin-width: 75px
      gutter-width: 4em

editor: source


