project:
  type: website
  output-dir: docs

website:
  title: "Big Fish card game"
  navbar:
    left:
      - href: rules.qmd
        text: Rules
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: lux
    css: styles.css
    toc: true



