project:
  type: website
  output-dir: docs
execute:
  freeze: auto

website:
  title: "Big Fish card game"
  repo-url: https://github.com/fishsizeproject/BigFishGame
  site-url: https://bigfishcardgame.com/
  page-navigation: false
  navbar:
    pinned: true
    collapse: true
    left:
      - href: rules.qmd
        text: Rules
      - href: wildCards.qmd
        text: Wildcards
      - href: resources.qmd
        text: Resources

# Different sidebars for different pages
website:
  sidebar:
  - id: rules-sidebar
    style: "docked"
    contents:
      - section: "How to play"
        contents:
        - text: "Setup"
          href: pages/rules.qmd#sec-section
        - text: "Gameplay"
          href: pages/rules.qmd#sec-gameplay
        - text: "Round end"
          href: pages/rules.qmd#sec-round-end
        - text: "Game end"
          href: pages/rules.qmd#sec-game-end
      - text: "-----"
      - section: "Cards"
        contents:
        - text: "Wildcards"
          href: pages/WildCards.qmd
        - text: "Round-end cards"
          href: pages/RoundEndCards.qmd
    type: dark
    border: false
  - id: cards-sidebar
    style: "docked"
    contents:
      - section: "Wildcards"
        contents:
        - text: "Catch and Release"
          href: pages/WildCards.qmd#sec-catch-and-release
        - text: "Centre for Marine Socioecology (CMS)"
          href: pages/WildCards.qmd#sec-centre-for-marine-socioecology
        - text: "Citizen science"
          href: pages/WildCards.qmd#sec-citizen-science
        - text: "Giant kelp"
          href: pages/WildCards.qmd#sec-giant-kelp
        - text: "Humpback whale"
          href: pages/WildCards.qmd#sec-humpback-whale
        - text: "Illegal fishing"
          href: pages/WildCards.qmd#sec-illegal-fishing
        - text: "Large shark"
          href: pages/WildCards.qmd#sec-large-shark
        - text: "Marine protected area"
          href: pages/WildCards.qmd#sec-marine-protected-area
        - text: "Poor water quality"
          href: pages/WildCards.qmd#sec-poor-water-quality
        - text: "Seaweed"
          href: pages/WildCards.qmd#sec-seaweed
        - text: "Severe weather"
          href: pages/WildCards.qmd#sec-severe-weather
        - text: "Shelfish reef"
          href: pages/WildCards.qmd#sec-shelfish-reef
      - text: "-----"
      - section: "Round-End Cards"
        contents:
        - text: "El Nino begins"
          href: pages/WildCards.qmd#sec-el-nino-begins
        - text: "Fisheries impose upper size limit"
          href: pages/WildCards.qmd#sec-fisheries-impose-upper-size-limit
        - text: "Fisheries research occurs"
          href: pages/WildCards.qmd#sec-fisheries-research-occurs
        - text: "Localised species extinction"
          href: pages/WildCards.qmd#sec-localised-species-extinction
        - text: "Long spined sea urchins arrive"
          href: pages/WildCards.qmd#sec-long-spined-sea-urchins-arrive
        - text: "Ocean acidification"
          href: pages/WildCards.qmd#sec-ocean-acidification
        - text: "Plankton swarm occurs"
          href: pages/WildCards.qmd#sec-plankton-swarm-occurs
        - text: "Seaweed planting occurs"
          href: pages/WildCards.qmd#sec-seaweed-planting-occurs
      - text: "-----"
      - text: " Game Setup & Rules"
        href: pages/resources_working.qmd
    type: dark
    border: false

format:
  html:
    logo: /resources/images/BigFish-notext.jpg
    theme: [lux, /resources/styling/theming.scss]
    css: /resources/styling/styles.css
    toc: false
    anchor-sections: false
    link-external-newwindow: true
    page-layout: full
    grid:
      sidebar-width: 250px
      body-width: 1450px
      margin-width: 100px
      gutter-width: 1.5em

editor: source


