---
pagetitle: How to Buy | BigFish Card Game
sidebar: false
description-meta: |
  We're currently crowdfunding the BigFish game, and the official campaign will launch on September 15, 2024!
include-after-body:
  text: |
    <script type="text/javascript" src="/resources/simple-countdown-timer/dist/script.js"></script>
---

::: {.column-screen .hero-img .hero-strip-page .img-container}
   
:::

::::::::::: {.grid .column-screen .mx-1 .mx-sm-2 .mx-md-3 .mx-xl-4 .spacer-1em .text-center style="--bs-columns: 1;"}
# We're crowdfunding!

To make the game available in Tasmania and worldwide and to run our engagement activities we are launching a **crowdfunding** campaign. Currently the game is not available for sale and you can only get it through crowdfunding. 
By pledging to this campaign you will secure your copy of the game and support education and engagement activities on marine science and sustainable recreational fishing. The campaign will launch on **September 15, 2024**.

<!-- An online ordering system is coming soon, but you can get your own copy of BigFish right now by emailing our team. -->

<!-- [Contact us](mailto:info@fishsizeproject.org){.h3 .btn .btn-secondary} -->
:::::::::::

<!-- begin timer grid -->
:::::: {.grid .column-screen .timerBox style="--bs-columns: 11;" .text-center .justify-contents-evenly .align-items-center .my-2 .mx-5}
::: {.g-col-4 .g-start-2 .g-start-md-1 .g-col-md-2 .mx-0 .px-0}
<h2 class="timertext" id="days">DD</h2>

### DAYS {.text-center .timerlabel .unlisted}
:::

::: {.g-col-1 .mx-0 .px-0}
<h2 class="timertext">:</h2>
:::

::: {.g-col-4 .g-col-md-2 .mx-0 .px-0}
<h2 class="timertext" id="hours">HH</h2>

### HOURS {.text-center .timerlabel .unlisted}
:::

::: {.g-col-1 .mx-0 .px-0 style="max-width: max(0px, calc((100vw - 768px)*999)); overflow: hidden;"}
<h2 class="timertext">:</h2>
:::

::: {.g-col-4 .g-start-2 .g-start-md-7 .g-col-md-2 .mx-0 .px-0}
<h2 class="timertext" id="minutes">MM</h2>

### MINS {.text-center .timerlabel .unlisted}
:::

::: {.g-col-1 .mx-0 .px-0}
<h2 class="timertext">:</h2>
:::

::: {.g-col-4 .g-col-md-2 .mx-0 .px-0}
<h2 class="timertext" id="seconds">SS</h2>

### SECS {.text-center .timerlabel .unlisted}
:::
<!-- end timer grid -->
::::::

<!-- subscribe to news section -->
::::::::::: {.grid .column-screen .mx-1 .mx-sm-2 .mx-md-3 .mx-xl-4 .spacer-1em .text-center style="--bs-columns: 1;"}
Would you like to be reminded about the crowdfunding launch? You can get the game, expansion pack, prints of amazing fish drawings signed by the artist, t-shirt and other prizes. You will get no more than one email per month and two reminders about the crowdfunding start. 

[Subscribe](https://forms.office.com/r/wVcaiUSxNF){.btn .btn-secondary}
:::::::::::
