---
pagetitle: Media & Events | BigFish Card Game
description-meta: |
  Meta description to go here
---

::: {.column-screen .hero-img .hero-strip-page}
   
:::

## Media & Events

Lots of fun and useful things will be added here soon. 


### Resources and popular science

**Short video about Asta's Pew fellowship project and vision for healthy oceans**

Story about the collaboration between Microsoft and Australian Government's Supervising Scientist Branch to build the baited remote underwter video image dataset from images at the Kakadu National park - [Citizen scientists, AI and cloud bond to boost billabong health in the Top End](https://news.microsoft.com/en-au/features/citizen-scientists-ai-and-cloud-bond-to-boost-billabong-health-in-the-top-end/)

### Science about the importance of large fish

A Scalable Open-Source Framework for Machine Learning-Based Image Collection, Annotation and Classification: A Case Study for Automatic Fish Species Identification. [2022.]{style="color:black;"} *Catarina NS Silva, Justas Dainys, Sean Simmons, Vincentas Vienožinskis, Asta Audzijonyte*. [Sustainability 14 (21), 14324](https://www.mdpi.com/2071-1050/14/21/14324)
